SELECT TITEL, ERSCHEINUNGSDATUM FROM AOLDATA.FILM WHERE ERSCHEINUNGSDATUM <= '01.01.2006';

SELECT CITY, POPULATION FROM AOLDATA.LOCATION WHERE POPULATION > 0;

SELECT AOLDATA.SPIELT_IN FROM AOLDATA.SPIELT_IN WHERE SCHAUSPIELER_SCHAUSPIELERID 