SELECT TITEL, ERSCHEINUNGSDATUM FROM AOLDATA.FILM 
WHERE ERSCHEINUNGSDATUM <= '01.01.2005';

SELECT CITY, POPULATION FROM AOLDATA.LOCATION 
WHERE POPULATION > 5000;

SELECT VORNAME, NACHNAME FROM AOLDATA.SCHAUSPIELER 
WHERE SCHAUSPIELERID = 4616;

SELECT TITEL FROM AOLDATA.SPIELT_IN, AOLDATA.FILM 
where SCHAUSPIELER_SCHAUSPIELERID = 66 
AND FILM_FILMID = FILMID;

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'google%';

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'myspace%';

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'facebook%';

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'aol%';

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'twitter%';

select COUNT(QUERY) FROM AOLDATA.QUERYDATA 
WHERE QUERY like 'youtube%';

select COUNT(QUERY), QUERY FROM AOLDATA.QUERYDATA 
WHERE QUERY like '%privacy%' group by QUERY;

select COUNT(QUERY), QUERY FROM AOLDATA.QUERYDATA 
WHERE QUERY like '%tor browser%' group by QUERY;


--- unfertig
select CLICKURL, QUERY, ANONID FROM AOLDATA.QUERYDATA
where CLICKURL IS NOT NULL
AND ANONID = 2334;

--distinct only shows (!) one time
--select distinct query from AOLDATA.QUERYDATA;

select QUERY from AOLDATA.QUERYDATA
where count(QUERY) = 1;


--https://stackoverflow.com/questions/6095567/sql-query-to-obtain-value-that-occurs-more-than-once
SELECT QUERY, COUNT(*)
FROM AOLDATA.QUERYDATA
GROUP BY QUERY
HAVING COUNT(*) <= 1;

