SELECT TITEL, ERSCHEINUNGSDATUM FROM AOLDATA.FILM WHERE ERSCHEINUNGSDATUM <= '01.01.2006';

SELECT CITY, POPULATION FROM AOLDATA.LOCATION WHERE POPULATION > 0;

SELECT VORNAME, NACHNAME FROM AOLDATA.SCHAUSPIELER WHERE SCHAUSPIELERID = 4616;

SELECT SCHAUSPIELER_SCHAUSPIELERID, FILM_FILMID FROM AOLDATA.SPIELT_IN, AOLDATA.FILM 
    WHERE AOLDATA.SPIELT_IN.SCHAUSPIELER_SCHAUSPIELERID = 4616; 
    WHERE AOLDATA.SPIELT_IN.SCHAUSPIELER_SCHAUSPIELERID = AOLDATA.SPIELT_IN.SCHAUSPIELER_SCHAUSPIELERID;